# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('t1', 'T1'), ('t2', 'T2'), ('t3', 'T3'), ('t4', 'T4'), ('t5plus', 'T5+')], max_length=20)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('loue', 'Loué'), ('maintenance', 'Maintenance'), ('archive', 'Archivé')], default='disponible', max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(default="Côte d'Ivoire", max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('surface_m2', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_chambres', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_salles_bain', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('nombre_etages', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('charges_incluses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('animaux_autorises', models.BooleanField(default=False)),
                ('fumeurs_acceptes', models.BooleanField(default=False)),
                ('photo_principale', models.ImageField(upload_to='biens/principales/')),
                ('photos_additionnelles', models.JSONField(blank=True, default=list)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Biens',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PhotoBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='biens/photos/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ordre', models.IntegerField(default=0)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('interet', models.BooleanField(default=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
            },
        ),
    ]
