# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photobien',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='biens.bien'),
        ),
        migrations.AddField(
            model_name='visite',
            name='bien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='biens.bien'),
        ),
        migrations.AddField(
            model_name='visite',
            name='locataire',
            field=models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['statut', 'ville'], name='biens_bien_statut_746e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['prix_mensuel'], name='biens_bien_prix_me_956ac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visite',
            unique_together={('bien', 'locataire', 'date_visite')},
        ),
    ]
