# Generated by Django 4.2.11 on 2026-06-18 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='prix_vente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bien',
            name='transaction_type',
            field=models.CharField(choices=[('location', 'Location'), ('vente', 'Vente'), ('both', 'Location & Vente')], default='location', help_text="Type d'opération pour ce bien", max_length=10),
        ),
        migrations.AlterField(
            model_name='bien',
            name='type_bien',
            field=models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('maison_basse', 'Maison basse'), ('studio', 'Studio'), ('t1', 'T1'), ('t2', 'T2'), ('t3', 'T3'), ('t4', 'T4'), ('t5plus', 'T5+'), ('duplex', 'Duplex'), ('immeuble', 'Immeuble'), ('residence', 'Résidence'), ('terrain', 'Terrain'), ('bureau', 'Bureau'), ('magasin', 'Magasin'), ('boutique', 'Boutique'), ('local_commercial', 'Local commercial'), ('entrepot', 'Entrepôt')], max_length=20),
        ),
    ]
