# Generated by Django 4.2.11 on 2026-06-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0003_bien_prix_vente_bien_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bien',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bien',
            name='quartier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bien',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bien',
            name='code_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['statut', 'commune'], name='biens_bien_statut_6186d1_idx'),
        ),
        migrations.AddIndex(
            model_name='bien',
            index=models.Index(fields=['latitude', 'longitude'], name='biens_bien_latitud_9c22ee_idx'),
        ),
    ]
