# Generated by Django 4.2.11 on 2026-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0004_add_quartier_commune_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
