# Generated by Django 4.2.11 on 2026-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date_expiration',
            field=models.DateTimeField(blank=True, help_text="Le bien reste bloqué pour les autres clients jusqu'à cette date (72h après confirmation).", null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='sans_visite',
            field=models.BooleanField(default=False, help_text='Le client a explicitement choisi de réserver sans avoir visité le bien.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'Demande en attente'), ('visite_demandee', 'Visite demandée avant validation'), ('confirmee', 'Confirmée'), ('refusee', 'Refusée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
    ]
