# Generated by Django 4.2.11 on 2026-07-13 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biens', '0007_reservation_date_expiration_reservation_sans_visite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisBien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_biens', to=settings.AUTH_USER_MODEL)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='biens.bien')),
            ],
            options={
                'verbose_name': 'Avis sur un bien',
                'verbose_name_plural': 'Avis sur les biens',
                'ordering': ['-date_creation'],
                'unique_together': {('bien', 'auteur')},
            },
        ),
    ]
