# Generated by Django 4.2.11 on 2026-07-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0008_avisbien'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='date_demande_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visite',
            name='demande_annulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visite',
            name='motif_annulation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
