version: '3.8'
services:
  bintou:
    build: .
    image: ghcr.io/${GITHUB_OWNER:-bintoudiaby}/projet_memoire:latest
    restart: always
    env_file: .env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - bintou_db
    labels:
      - "traefik.enable=true"
      - "traefik.public=true"
      - "traefik.http.routers.bintou.rule=Host(`bintou.enlignes.com`)"
      - "traefik.http.routers.bintou.entrypoints=websecure"
      - "traefik.http.services.bintou.loadbalancer.server.port=8000"
      - "traefik.docker.network=traefik_public"
    networks:
      - traefik_public

  bintou_db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=immobilier_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik_public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d immobilier_prod"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  static_volume:
  media_volume:
  postgres_data:
    driver: local

networks:
  traefik_public:
    external: true
