# Generated by Django 4.2.11 on 2026-06-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='phase',
            field=models.CharField(choices=[('commercial', 'Commercial'), ('locataire', 'Locataire'), ('sav', 'SAV / Après achat')], default='commercial', max_length=20),
        ),
    ]
