# Generated by Django 4.2.11 on 2026-06-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0005_visite_statut'),
        ('construction', '0001_initial'),
        ('messagerie', '0002_conversation_phase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversation',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='construction.projetconstruction'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='bien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='biens.bien'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('bien__isnull', False)), fields=('bien', 'demandeur'), name='unique_bien_demandeur'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('projet__isnull', False)), fields=('projet', 'demandeur'), name='unique_projet_demandeur'),
        ),
    ]
