# Generated by Django 4.2.11 on 2026-07-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0003_alter_conversation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='archive_demandeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='archive_proprietaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='est_modifie',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
