# Generated by Django 4.2.11 on 2026-07-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagerie', '0004_conversation_archive_demandeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='supprime_demandeur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='supprime_proprietaire',
            field=models.BooleanField(default=False),
        ),
    ]
