# Generated by Django 6.0.3 on 2026-05-01 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afficher_revenus', models.BooleanField(default=True)),
                ('afficher_contrats', models.BooleanField(default=True)),
                ('afficher_alertes', models.BooleanField(default=True)),
                ('afficher_historique', models.BooleanField(default=True)),
                ('notifications_email_activees', models.BooleanField(default=True)),
                ('notifier_paiement_recu', models.BooleanField(default=True)),
                ('notifier_impaye', models.BooleanField(default=True)),
                ('notifier_new_demande', models.BooleanField(default=True)),
                ('langue', models.CharField(choices=[('fr-FR', 'Français'), ('en-US', 'English')], default='fr-FR', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20)),
                ('widgets_actifs', models.JSONField(blank=True, default=list)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_dashboard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration Dashboard',
                'verbose_name_plural': 'Configurations Dashboard',
            },
        ),
        migrations.CreateModel(
            name='StatistiquesProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proprietes', models.IntegerField(default=0)),
                ('nombre_contrats_actifs', models.IntegerField(default=0)),
                ('nombre_locataires', models.IntegerField(default=0)),
                ('revenu_mensuel_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenu_annuel_estime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('revenu_recu_ce_mois', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_impaye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('nombre_contrats_avec_impaye', models.IntegerField(default=0)),
                ('taux_collecte_pourcentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.OneToOneField(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_proprietaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistiques Propriétaire',
                'verbose_name_plural': 'Statistiques Propriétaires',
            },
        ),
        migrations.CreateModel(
            name='TableauBordLocataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contrats_actifs', models.IntegerField(default=0)),
                ('nombre_recherches_sauvegardees', models.IntegerField(default=0)),
                ('prochain_paiement_date', models.DateField(blank=True, null=True)),
                ('prochain_paiement_montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paiements_en_retard', models.IntegerField(default=0)),
                ('montant_en_retard', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_biens_favoris', models.IntegerField(default=0)),
                ('nombre_visites_programmees', models.IntegerField(default=0)),
                ('date_derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('locataire', models.OneToOneField(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='tableau_bord_locataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tableau de Bord Locataire',
                'verbose_name_plural': 'Tableaux de Bord Locataires',
            },
        ),
        migrations.CreateModel(
            name='AlerteSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severite', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('resolue', 'Résolue'), ('ignoree', 'Ignorée')], default='active', max_length=20)),
                ('tout_le_monde', models.BooleanField(default=False)),
                ('proprietaires', models.BooleanField(default=False)),
                ('locataires', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('utilisateurs_specifiques', models.ManyToManyField(blank=True, related_name='alertes_specifiques', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte Système',
                'verbose_name_plural': 'Alertes Système',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'severite'], name='dashboard_a_statut_a1bf4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('connexion', 'Connexion'), ('creation_bien', 'Création de bien'), ('creation_contrat', 'Création de contrat'), ('facture_generee', 'Facture générée'), ('paiement_recu', 'Paiement reçu'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('export', 'Export'), ('import', 'Import'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('date_activite', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_activite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Activité',
                'verbose_name_plural': 'Logs Activité',
                'ordering': ['-date_activite'],
                'indexes': [models.Index(fields=['utilisateur', 'date_activite'], name='dashboard_l_utilisa_a2b464_idx'), models.Index(fields=['type_activite'], name='dashboard_l_type_ac_6c3997_idx')],
            },
        ),
        migrations.CreateModel(
            name='RapportMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois')),
                ('nombre_proprietes', models.IntegerField()),
                ('nombre_contrats_actifs', models.IntegerField()),
                ('nombre_locataires', models.IntegerField()),
                ('revenu_attendu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revenu_recu', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_impaye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taux_collecte', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='rapports/')),
                ('proprietaire', models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='rapports_mensuels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport Mensuel',
                'verbose_name_plural': 'Rapports Mensuels',
                'ordering': ['-mois'],
                'unique_together': {('proprietaire', 'mois')},
            },
        ),
    ]
