# Generated by Django 4.2.11 on 2026-07-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('message', 'Nouveau message'), ('visite', 'Visite'), ('reservation', 'Réservation'), ('devis', 'Devis'), ('reclamation', 'Réclamation'), ('paiement', 'Paiement'), ('contrat', 'Contrat'), ('convocation', 'Convocation'), ('systeme', 'Système')], max_length=20),
        ),
    ]
