# Generated by Django 4.2.11 on 2026-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='dashboard_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
