# Generated by Django 4.2.11 on 2026-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_company_adresse_company_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='accepte_appels',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='afficher_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='afficher_telephone',
            field=models.BooleanField(default=True),
        ),
    ]
