# Generated by Django 4.2.11 on 2026-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_utilisateur_accepte_appels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='otp_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='otp_expire_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
