# Generated by Django 4.2.11 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_utilisateur_otp_code_utilisateur_otp_expire_le'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='numero_ncc',
            field=models.CharField(blank=True, default='', help_text='Attribué par la DGI. Requis pour la certification FNE et comme identifiant vendeur.', max_length=20, verbose_name='Numéro de Compte Contribuable (NCC)'),
        ),
        migrations.AddField(
            model_name='company',
            name='numero_rccm',
            field=models.CharField(blank=True, default='', help_text='Registre du Commerce et du Crédit Mobilier — mention obligatoire OHADA (pied de page des factures).', max_length=30, verbose_name='Numéro RCCM'),
        ),
        migrations.AddField(
            model_name='company',
            name='taux_tva_loyer',
            field=models.CharField(choices=[('TVA', 'TVA normal 18%'), ('TVAB', 'TVA réduit 9%'), ('TVAC', 'Exonération conventionnelle 0%'), ('TVAD', 'Exonération légale 0%')], default='TVAD', help_text="Code transmis à la FNE pour chaque facture de loyer. Par défaut : exonération légale (traitement standard de la location nue à usage d'habitation) — à confirmer avec votre comptable.", max_length=4, verbose_name='Régime TVA appliqué aux loyers'),
        ),
    ]
