# Generated by Django 4.2.11 on 2026-07-13 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_company_numero_ncc_company_numero_rccm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(limit_choices_to={'role': 'locataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='avis_entreprises', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='utilisateurs.company')),
            ],
            options={
                'verbose_name': 'Avis sur une entreprise',
                'verbose_name_plural': 'Avis sur les entreprises',
                'ordering': ['-date_creation'],
                'unique_together': {('company', 'auteur')},
            },
        ),
    ]
