# Generated by Django 4.2.11 on 2026-07-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_avisentreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='delai_reponse_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Délai de réponse habituel affiché aux clients, en minutes (ex: 5, 60).', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='disponible_maintenant',
            field=models.BooleanField(default=True, help_text="Décochez pour afficher « actuellement indisponible » même pendant vos horaires d'ouverture."),
        ),
        migrations.AddField(
            model_name='company',
            name='horaires',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {'lundi': '08:00-18:00', 'dimanche': ''} — vide ou absent = fermé ce jour-là."),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
