# Generated by Django 4.2.11 on 2026-07-14 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0009_company_delai_reponse_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(choices=[('commercial', 'Commercial'), ('comptable', 'Comptable'), ('gestionnaire_locatif', 'Gestionnaire locatif'), ('assistant', 'Assistant')], default='assistant', max_length=30)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('invite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborateurs_invites', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaborateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collaborateur',
                'verbose_name_plural': 'Collaborateurs',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
