# Generated by Django 4.2.11 on 2026-07-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0010_collaborateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateur',
            name='acces_commercial',
            field=models.BooleanField(default=False, help_text='Biens, réservations, devis, messages, clients, rendez-vous'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='acces_comptable',
            field=models.BooleanField(default=False, help_text='Facturation, validation des paiements, statistiques'),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='acces_gestion_locative',
            field=models.BooleanField(default=False, help_text='Contrats, réclamations'),
        ),
    ]
