# Generated by Django 4.2.11 on 2026-07-15 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0011_collaborateur_acces_commercial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('a_faire', 'À faire'), ('fait', 'Faite')], default='a_faire', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_terminee', models.DateTimeField(blank=True, null=True)),
                ('assignee_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches_recues', to=settings.AUTH_USER_MODEL)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taches_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['statut', 'date_limite', '-date_creation'],
            },
        ),
    ]
