# Generated by Django 4.2.11 on 2026-07-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0014_company_facebook_company_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date_verification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='document_rccm',
            field=models.FileField(blank=True, help_text='Justificatif du Registre du Commerce et du Crédit Mobilier (PDF ou photo).', null=True, upload_to='companies/rccm/', verbose_name='Document RCCM'),
        ),
        migrations.AddField(
            model_name='company',
            name='motif_rejet',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='statut_verification',
            field=models.CharField(choices=[('en_attente', 'En attente de vérification'), ('validee', 'Vérifiée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=10),
        ),
    ]
