# Generated by Django 4.2.11 on 2026-07-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0015_company_date_verification_company_document_rccm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='type_compte',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('entreprise', 'Entreprise immobilière')], default='entreprise', max_length=12),
        ),
    ]
