# Generated by Django 4.2.11 on 2026-07-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0016_company_type_compte'),
    ]

    operations = [
        migrations.AddField(
            model_name='proprietaireprofile',
            name='date_verification_identite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proprietaireprofile',
            name='motif_rejet_identite',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='proprietaireprofile',
            name='piece_identite',
            field=models.FileField(blank=True, null=True, upload_to='documents/proprietaires/pieces_identite/'),
        ),
        migrations.AddField(
            model_name='proprietaireprofile',
            name='statut_verification_identite',
            field=models.CharField(choices=[('en_attente', 'En attente de vérification'), ('validee', 'Vérifiée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=10),
        ),
        migrations.AddField(
            model_name='proprietaireprofile',
            name='type_piece_identite',
            field=models.CharField(blank=True, choices=[('cni', "Carte Nationale d'Identité"), ('passeport', 'Passeport'), ('attestation', "Attestation d'identité")], default='', max_length=15),
        ),
    ]
