# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('contrat', 'Contrat'), ('avenant', 'Avenant'), ('quittance', 'Quittance'), ('recon_dette', 'Reconnaissance de dette'), ('cert_residence', 'Certificat de résidence')], max_length=20)),
                ('fichier', models.FileField(upload_to='documents/contrats/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Contrat',
                'verbose_name_plural': 'Documents Contrat',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.DateField(help_text='Premier jour du mois de la facturation')),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_recu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_limite', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('recu', 'Reçu'), ('retard_mineur', 'Retard mineur'), ('retard_majeur', 'Retard majeur'), ('impaye', 'Impayé')], default='en_attente', max_length=20)),
                ('raison_retard', models.TextField(blank=True, null=True)),
                ('montant_penalites', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-mois'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(max_length=50, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('date_signature', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='brouillon', max_length=20)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_depot_garantie', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('charges_mensuelles', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nombre_mois_minimum', models.IntegerField(default=12)),
                ('jour_paiement', models.IntegerField(default=1)),
                ('modalites_resilition', models.TextField(blank=True, null=True)),
                ('conditions_speciales', models.TextField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='biens.bien')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
    ]
