# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='locataire',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'locataire'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_souscrits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrat',
            name='proprietaire',
            field=models.ForeignKey(limit_choices_to={'role': 'proprietaire'}, on_delete=django.db.models.deletion.PROTECT, related_name='contrats_proposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentcontrat',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contrats.contrat'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='contrats.contrat'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['statut', 'date_debut'], name='contrats_co_statut_6a9d5c_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['locataire'], name='contrats_co_locatai_ec9442_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['statut', 'mois'], name='contrats_pa_statut_d4b56a_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['contrat', 'statut'], name='contrats_pa_contrat_725dc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paiement',
            unique_together={('contrat', 'mois')},
        ),
    ]
