# Generated by Django 4.2.11 on 2026-07-07 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contrats', '0003_reclamation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_remboursement_caution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_caution_rembourse',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contrat',
            name='motif_retenue_caution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contrat',
            name='statut_caution',
            field=models.CharField(choices=[('non_traitee', 'Non traitée'), ('retenue', 'Retenue (partiellement ou totalement)'), ('remboursee', 'Remboursée')], default='non_traitee', max_length=20),
        ),
        migrations.CreateModel(
            name='EtatDesLieux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_etat', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('etat_general', models.CharField(choices=[('bon', 'Bon état'), ('moyen', 'État moyen'), ('mauvais', 'Mauvais état')], default='bon', max_length=10)),
                ('observations', models.TextField(blank=True, default='')),
                ('date_realisation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etats_des_lieux', to='contrats.contrat')),
                ('realise_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etats_des_lieux_realises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'État des lieux',
                'verbose_name_plural': 'États des lieux',
                'ordering': ['-date_realisation'],
                'unique_together': {('contrat', 'type_etat')},
            },
        ),
    ]
