# Generated by Django 4.2.11 on 2026-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biens', '0006_reservation'),
        ('contrats', '0004_contrat_date_remboursement_caution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_envoi_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='reservation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrat', to='biens.reservation'),
        ),
        migrations.AlterField(
            model_name='contrat',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente_signature', 'En attente de signature du locataire'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu'), ('resilie', 'Résilié')], default='brouillon', max_length=20),
        ),
    ]
