# Generated by Django 4.2.11 on 2026-07-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0005_contrat_date_envoi_signature_contrat_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='jours_avant_convocation',
            field=models.PositiveIntegerField(default=21, verbose_name='Convocation après (jours de retard)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='jours_avant_frais',
            field=models.PositiveIntegerField(default=14, verbose_name='Frais de retard après (jours)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='jours_avant_rappel',
            field=models.PositiveIntegerField(default=7, verbose_name='Rappel après (jours de retard)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='montant_frais_retard',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 = aucun frais de retard appliqué.', max_digits=10, verbose_name='Montant des frais de retard (FCFA)'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='texte_contrat_signe',
            field=models.TextField(blank=True, default=''),
        ),
    ]
