# Generated by Django 4.2.11 on 2026-07-12 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0007_contrat_est_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='date_alerte_grave_envoyee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_frais_appliques',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_rappel_retard_envoye',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Convocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(default='Retard de paiement', max_length=255)),
                ('date_convocation', models.DateTimeField()),
                ('lieu', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('confirmee', 'Présence confirmée'), ('report_demande', 'Report demandé'), ('honoree', 'Honorée (situation régularisée)'), ('absence', 'Absence constatée'), ('cloturee', 'Dossier clôturé')], default='envoyee', max_length=20)),
                ('motif_report', models.TextField(blank=True, default='')),
                ('nouvelle_date_proposee', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='contrats.contrat')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocations', to='contrats.paiement')),
            ],
            options={
                'verbose_name': 'Convocation',
                'verbose_name_plural': 'Convocations',
                'ordering': ['-date_creation'],
            },
        ),
    ]
