# Generated by Django 4.2.11 on 2026-07-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0008_paiement_date_alerte_grave_envoyee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiseEnDemeure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(default='Mise en demeure pour non-paiement', max_length=255)),
                ('date_limite_regularisation', models.DateField()),
                ('envoi_application', models.BooleanField(default=True)),
                ('envoi_email', models.BooleanField(default=False)),
                ('envoi_pdf', models.BooleanField(default=False)),
                ('message_complementaire', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('regularisee', 'Régularisée'), ('expiree', 'Expirée'), ('delai_supplementaire', 'Délai supplémentaire accordé'), ('cloturee', 'Dossier clôturé'), ('procedure', 'Procédure contentieuse engagée')], default='envoyee', max_length=25)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mise en demeure',
                'verbose_name_plural': 'Mises en demeure',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='contrat',
            name='jours_avant_convocation',
        ),
        migrations.AddField(
            model_name='contrat',
            name='jours_avant_mise_en_demeure',
            field=models.PositiveIntegerField(default=21, verbose_name='Mise en demeure après (jours de retard)'),
        ),
        migrations.DeleteModel(
            name='Convocation',
        ),
        migrations.AddField(
            model_name='miseendemeure',
            name='contrat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_en_demeure', to='contrats.contrat'),
        ),
        migrations.AddField(
            model_name='miseendemeure',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mises_en_demeure', to='contrats.paiement'),
        ),
    ]
