# Generated by Django 4.2.11 on 2026-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0009_miseendemeure_remove_contrat_jours_avant_convocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrat',
            name='date_resiliation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrat',
            name='motif_resiliation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
