# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.CharField(max_length=255)),
                ('nombre_resultats', models.IntegerField(default=0)),
                ('date_recherche', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique Recherche',
                'verbose_name_plural': 'Historiques Recherches',
                'ordering': ['-date_recherche'],
            },
        ),
        migrations.CreateModel(
            name='RechercheSauvegardee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('villes', models.JSONField(blank=True, default=list)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_chambres_min', models.IntegerField(blank=True, null=True)),
                ('nombre_chambres_max', models.IntegerField(blank=True, null=True)),
                ('surface_min', models.IntegerField(blank=True, null=True)),
                ('types_bien', models.JSONField(blank=True, default=list)),
                ('equipements', models.JSONField(blank=True, default=list)),
                ('animaux_autorises', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_recherche', models.DateTimeField(blank=True, null=True)),
                ('nombre_utilisations', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recherche Sauvegardée',
                'verbose_name_plural': 'Recherches Sauvegardées',
                'ordering': ['-date_derniere_recherche'],
            },
        ),
        migrations.CreateModel(
            name='BienFavori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='biens.bien')),
            ],
            options={
                'verbose_name': 'Bien Favori',
                'verbose_name_plural': 'Biens Favoris',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
