# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recherche', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bienfavori',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biens_favoris', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquerecherche',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_recherches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recherchesauvegardee',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_sauvegardees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='bienfavori',
            unique_together={('utilisateur', 'bien')},
        ),
    ]
