"""
Django settings for immobilier_config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import pillow_avif  # noqa: enregistre le support AVIF pour Pillow/ImageField (photos uploadées)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x^@#cgp95_+u&_ylm*uu-us#w9r9_9xmyh=f_e*db7-5o^m_m0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 10.0.2.2 = alias que l'émulateur Android utilise pour joindre l'hôte (voir
# ApiConfig.baseUrl côté Flutter, --dart-define=API_BASE_URL=http://10.0.2.2:8000).
# Sans cette entrée, Django rejette la requête avec DisallowedHost avant même
# de poser le cookie csrftoken (le fallback DEBUG=True n'autorise que
# localhost/127.0.0.1/[::1], pas 10.0.2.2).
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '10.0.2.2']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_filters',
    'django.contrib.humanize',
    
    # Local apps
    'utilisateurs.apps.UtilisateursConfig',
    'biens.apps.BiensConfig',
    'contrats.apps.ContratsConfig',
    'facturation.apps.FacturationConfig',
    'recherche.apps.RechercheConfig',
    'dashboard.apps.DashboardConfig',
    'messagerie',
    'construction',
    'assistant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'immobilier_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'immobilier_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# Lu depuis .env (voir .env.example) — SQLite par défaut si DB_ENGINE n'est
# pas défini, pour ne rien casser en dev local sans .env. En production,
# définir DB_ENGINE=django.db.backends.postgresql + DB_NAME/DB_USER/
# DB_PASSWORD/DB_HOST/DB_PORT pour bénéficier d'un stockage persistant
# (SQLite est un simple fichier sur disque : sur la plupart des hébergeurs
# cloud le disque n'est pas persistant et le fichier est réinitialisé à
# chaque redéploiement/redémarrage — cause du "je perds mes données en ligne").
db_engine = config('DB_ENGINE', default='django.db.backends.sqlite3')
if db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': db_engine,
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
# Ajouter le dossier `static/` à la racine du projet pour le dev
from pathlib import Path as _Path
STATICFILES_DIRS = [BASE_DIR / 'static']

# CORS configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Session : utilisée par le site web (Django templates) et l'API navigable
        'rest_framework.authentication.SessionAuthentication',
        # JWT : utilisée par l'application mobile (header Authorization: Bearer <token>)
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # Génération du schéma OpenAPI (Swagger / Redoc) via drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Documentation de l'API — drf-spectacular (OpenAPI 3)
SPECTACULAR_SETTINGS = {
    'TITLE': "API ImmoGérer",
    'DESCRIPTION': "API REST de la plateforme de gestion locative ImmoGérer.",
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Authentification par token JWT (application mobile) — djangorestframework-simplejwt
# Sans stockage en base : les tokens sont signés, rien n'est enregistré côté DB.
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),   # token d'accès valable 12 h
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),   # token de rafraîchissement valable 30 j
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Modèle d'utilisateur personnalisé
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'

# Redirection après connexion / déconnexion
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Email (OTP / confirmation de compte) — lu depuis .env, jamais commité.
# En l'absence de .env (ex. environnement de test), retombe sur la console
# pour ne jamais bloquer ni tenter d'envoyer un vrai email par erreur.
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='ImmoGérer <noreply@immogerer.local>')

# Stripe (paiement par carte bancaire) — clé restreinte de test, lue depuis .env.
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')

# FNE — Facture Normalisée Électronique (DGI Côte d'Ivoire). URL de test par
# défaut (sandbox DGI) ; FNE_API_KEY reste vide tant que l'entreprise n'a pas
# terminé son inscription/validation auprès de la DGI (voir facturation/fne_service.py).
FNE_API_URL = config('FNE_API_URL', default='http://54.247.95.108/ws')
FNE_API_KEY = config('FNE_API_KEY', default='')
