# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rappel', models.CharField(choices=[('premier_rappel', 'Premier rappel (2 jours après)'), ('deuxieme_rappel', 'Deuxième rappel (7 jours après)'), ('avis_final', 'Avis final (15 jours après)')], max_length=20)),
                ('date_programmee', models.DateTimeField()),
                ('date_envoi_reel', models.DateTimeField(blank=True, null=True)),
                ('est_envoye', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rappel de Paiement',
                'verbose_name_plural': 'Rappels de Paiement',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unique', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_emission', models.DateTimeField(blank=True, null=True)),
                ('date_echéance', models.DateField()),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('montant_loyer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_autres', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_taxe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('generee', 'Générée'), ('envoyee', 'Envoyée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/pdf/')),
                ('tentatives_envoi', models.IntegerField(default=0)),
                ('dernier_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='contrats.contrat')),
                ('paiement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='contrats.paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification Push')], max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('envoyee', 'Envoyée'), ('lue', 'Lue'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message_erreur', models.TextField(blank=True, null=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='facturation.facture')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
    ]
