# Generated by Django 6.0.3 on 2026-04-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0002_initial'),
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rappelpaiement',
            name='notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturation.notification'),
        ),
        migrations.AddField(
            model_name='rappelpaiement',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels', to='contrats.paiement'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut', 'date_echéance'], name='facturation_statut_f83bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['contrat', 'date_generation'], name='facturation_contrat_9fda73_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'statut'], name='facturation_utilisa_496727_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['facture'], name='facturation_facture_f82f02_idx'),
        ),
        migrations.AddIndex(
            model_name='rappelpaiement',
            index=models.Index(fields=['est_envoye', 'date_programmee'], name='facturation_est_env_5ead02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rappelpaiement',
            unique_together={('paiement', 'type_rappel')},
        ),
    ]
