# Generated by Django 4.2.11 on 2026-07-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='mode_paiement',
            field=models.CharField(blank=True, choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN MoMo'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='reference_transaction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
