# Generated by Django 4.2.11 on 2026-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_facture_mode_paiement_facture_reference_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fne_certifiee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_certifiee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_erreur',
            field=models.TextField(blank=True, default='', help_text="Dernier message d'erreur si la certification auprès de la DGI a échoué."),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_reference',
            field=models.CharField(blank=True, default='', help_text='Numéro de facture normalisée renvoyé par la DGI après certification (série annuelle ininterrompue).', max_length=50, verbose_name='Numéro FNE'),
        ),
        migrations.AddField(
            model_name='facture',
            name='fne_token',
            field=models.CharField(blank=True, default='', help_text='URL de vérification renvoyée par la DGI, encodée en QR code sur la facture.', max_length=200, verbose_name='Jeton de vérification FNE'),
        ),
    ]
