# Generated by Django 4.2.11 on 2026-07-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_facture_fne_certifiee_facture_fne_certifiee_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_declaration_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='motif_rejet_paiement',
            field=models.TextField(blank=True, default='', help_text="Raison indiquée par le propriétaire s'il signale un problème sur un paiement déclaré."),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero_paiement_declare',
            field=models.CharField(blank=True, default='', help_text='Numéro mobile money saisi par le locataire lors de la déclaration du paiement.', max_length=20),
        ),
        migrations.AlterField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('generee', 'Générée'), ('envoyee', 'Envoyée'), ('en_validation', 'En attente de validation'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=20),
        ),
    ]
