# Generated by Django 4.2.11 on 2026-07-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturation', '0005_facture_date_declaration_paiement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenPaiementEnregistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('wave', 'Wave'), ('orange_money', 'Orange Money'), ('mtn', 'MTN MoMo'), ('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement bancaire')], max_length=20)),
                ('numero', models.CharField(max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyens_paiement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moyen de paiement enregistré',
                'verbose_name_plural': 'Moyens de paiement enregistrés',
                'ordering': ['-date_modification'],
                'unique_together': {('utilisateur', 'mode_paiement')},
            },
        ),
    ]
