# Generated by Django 4.2.11 on 2026-07-12 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturation', '0006_moyenpaiementenregistre'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVousPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demandee', models.DateTimeField(verbose_name='Date/heure demandée par le locataire')),
                ('message', models.TextField(blank=True, default='')),
                ('date_proposee', models.DateTimeField(blank=True, null=True, verbose_name="Autre créneau proposé par l'entreprise")),
                ('date_confirmee', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de réponse'), ('contre_proposition', 'Autre créneau proposé'), ('confirme', 'Confirmé'), ('refuse', 'Refusé'), ('honore', 'Honoré (paiement reçu)')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, default='')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous_paiement', to='facturation.facture')),
                ('locataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_paiements_demandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous de paiement',
                'verbose_name_plural': 'Rendez-vous de paiement',
                'ordering': ['-date_creation'],
            },
        ),
    ]
