# Generated by Django 4.2.11 on 2026-07-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_rendezvouspaiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='est_archive',
            field=models.BooleanField(default=False),
        ),
    ]
