# Generated by Django 4.2.11 on 2026-06-28 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biens', '0005_visite_statut'),
        ('utilisateurs', '0003_company_utilisateur_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.IntegerField(default=0)),
                ('statut', models.CharField(choices=[('a_venir', 'A venir'), ('en_cours', 'En cours'), ('termine', 'Termine')], default='a_venir', max_length=20)),
                ('date_prevue', models.DateField(blank=True, null=True)),
                ('date_reelle', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etape de chantier',
                'verbose_name_plural': 'Etapes de chantier',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='RealisationConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='construction/realisations/')),
                ('annee', models.IntegerField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=255)),
                ('type_projet', models.CharField(blank=True, max_length=50)),
                ('ordre', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realisations', to='utilisateurs.company')),
            ],
            options={
                'verbose_name': 'Realisation',
                'verbose_name_plural': 'Realisations',
                'ordering': ['ordre', '-annee'],
            },
        ),
        migrations.CreateModel(
            name='ProjetConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_projet', models.CharField(choices=[('villa', 'Villa'), ('duplex', 'Duplex'), ('immeuble', 'Immeuble'), ('magasin', 'Magasin / Commerce'), ('bureau', 'Bureau'), ('renovation', 'Renovation'), ('autre', 'Autre')], max_length=20)),
                ('superficie', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True)),
                ('a_terrain', models.BooleanField(default=False)),
                ('localisation_terrain', models.CharField(blank=True, max_length=255)),
                ('budget_estime', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('devis_envoye', 'Devis envoye'), ('accepte', 'Accepte'), ('en_cours', 'En cours'), ('termine', 'Termine'), ('annule', 'Annule')], default='en_attente', max_length=20)),
                ('pourcentage_avancement', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_construction', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_recus', to='utilisateurs.company')),
                ('terrain_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_construction', to='biens.bien')),
            ],
            options={
                'verbose_name': 'Projet de construction',
                'verbose_name_plural': 'Projets de construction',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='ProfilConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('annee_creation', models.IntegerField(blank=True, null=True)),
                ('nb_projets_realises', models.IntegerField(default=0)),
                ('specialites', models.JSONField(blank=True, default=list)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('site_web', models.CharField(blank=True, max_length=255)),
                ('note_moyenne', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_construction', to='utilisateurs.company')),
            ],
            options={
                'verbose_name': 'Profil construction',
                'verbose_name_plural': 'Profils construction',
            },
        ),
        migrations.CreateModel(
            name='PhotoChantier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chantiers/photos/')),
                ('legende', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='construction.etapechantier')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_chantier', to='construction.projetconstruction')),
            ],
            options={
                'verbose_name': 'Photo de chantier',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.AddField(
            model_name='etapechantier',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='construction.projetconstruction'),
        ),
    ]
