# Generated by Django 4.2.11 on 2026-06-29 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetconstruction',
            name='date_rdv',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetconstruction',
            name='notes_rdv',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='NotificationConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('nouveau_devis', 'Nouveau devis reçu'), ('rdv_propose', 'RDV proposé'), ('rdv_modifie', 'RDV modifié par le client'), ('statut_change', 'Statut du projet modifié'), ('etape_change', 'Étape mise à jour')], max_length=30)),
                ('message', models.TextField()),
                ('lue', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs_construction', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='construction.projetconstruction')),
            ],
            options={
                'verbose_name': 'Notification construction',
                'ordering': ['-cree_le'],
            },
        ),
    ]
