# Generated by Django 4.2.11 on 2026-07-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0002_projetconstruction_date_rdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetconstruction',
            name='rdv_confirme',
            field=models.BooleanField(default=False),
        ),
    ]
