# Generated by Django 4.2.11 on 2026-07-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_alter_notificationconstruction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationconstruction',
            name='type',
            field=models.CharField(choices=[('nouveau_devis', 'Nouveau devis reçu'), ('rdv_propose', 'RDV proposé'), ('rdv_modifie', 'RDV modifié par le client'), ('rdv_confirme', 'RDV confirmé par le client'), ('rdv_annule', "RDV annulé par l'entreprise"), ('statut_change', 'Statut du projet modifié'), ('etape_change', 'Étape mise à jour')], max_length=30),
        ),
    ]
