# Generated by Django 4.2.11 on 2026-07-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetconstruction',
            name='rdv_termine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationconstruction',
            name='type',
            field=models.CharField(choices=[('nouveau_devis', 'Nouveau devis reçu'), ('rdv_propose', 'RDV proposé'), ('rdv_modifie', 'RDV modifié par le client'), ('rdv_confirme', 'RDV confirmé par le client'), ('rdv_annule', "RDV annulé par l'entreprise"), ('rdv_termine', 'RDV terminé — devis débloqué'), ('statut_change', 'Statut du projet modifié'), ('etape_change', 'Étape mise à jour')], max_length=30),
        ),
        migrations.AlterField(
            model_name='projetconstruction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projetconstruction',
            name='type_projet',
            field=models.CharField(choices=[('villa', 'Villa'), ('duplex', 'Duplex'), ('immeuble', 'Immeuble'), ('magasin', 'Magasin / Commerce'), ('bureau', 'Bureau'), ('renovation', 'Renovation'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
