# Generated by Django 4.2.11 on 2026-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_projetconstruction_rdv_termine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetconstruction',
            name='rdv_termine',
        ),
        migrations.AlterField(
            model_name='notificationconstruction',
            name='type',
            field=models.CharField(choices=[('nouveau_devis', 'Nouveau devis reçu'), ('rdv_propose', 'RDV proposé'), ('rdv_modifie', 'RDV proposé/modifié par le client'), ('rdv_confirme', "RDV confirmé par l'entreprise — devis débloqué"), ('rdv_annule', 'RDV annulé'), ('statut_change', 'Statut du projet modifié'), ('etape_change', 'Étape mise à jour')], max_length=30),
        ),
    ]
